from typing import Protocol, List, Tuple, Dict, Any

class StorageBackend(Protocol):
    def name(self) -> str: ...
    def initialize(self, dim: int, **kwargs) -> None: ...
    def index_documents(self, ids: List[str], vectors, metadatas: List[Dict[str, Any]]) -> None: ...
    def query(self, query_vec, k: int) -> List[Tuple[str, float]]: ...
    def add_documents(self, ids: List[str], vectors, metadatas: List[Dict[str, Any]]) -> None: ...
    def close(self) -> None: ...
